name: wordindex build
on: 
  push:
  workflow_dispatch:
jobs:
  wordindex:
    runs-on: ubuntu-latest

    steps:
      - name: cancel previous run
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with: 
          ref: ${{ github.head_ref }}
          fetch-depth: 10
          submodules: 'true'

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: build word index
        run: |
          cd lib/_indexer
          yarn install
          yarn pageindex Tol Tolkāppiyam
          yarn todb Tol
          yarn dbtohtml Tolkāppiyam
          cd ../..
          git pull

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: automatic wordindex update
          file_pattern: index.html wordindex.db wordindex.html
          commit_user_name: Tamilex Bot
